name: SSL Firmware CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev python3-venv

      - name: Install Zephyr SDK
        run: |
          mkdir -p $HOME/.local/opt
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.8/zephyr-sdk-0.16.8_linux-x86_64.tar.xz -O - | xz -d -c - | tar xv -C $HOME/.local/opt
          $HOME/.local/opt/zephyr-sdk-0.16.8/setup.sh -c
          echo "ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
          echo "ZEPHYR_SDK_INSTALL_DIR=$HOME/.local/opt/zephyr-sdk-0.16.8" >> $GITHUB_ENV

      - name: Setup Python environment and West
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install west

      - name: Initialize West and update
        run: |
          source .venv/bin/activate
          mkdir ssl && cd ssl
          west init -m https://github.com/roboime/ssl_firmware.git
          west update
          west config build.board roboime_nucleo_h723zg
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build all applications
        run: |
          source .venv/bin/activate
          cd ssl
          for app in ssl_firmware/applications/*; do
            if [ -d "$app" ]; then
              app_name=$(basename "$app")
              echo "Building $app_name"
              west build -d build/$app_name -p auto $app
            fi
          done

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: ssl/build/*/zephyr/zephyr.*