name: Zephyr Build

on:
  push:
    branches: [ main, dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build gperf ccache dfu-util device-tree-compiler wget python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev
        
    - name: Install West
      run: |
        pip3 install west
        west init -m https://github.com/zephyrproject-rtos/zephyr
        west update
        west zephyr-export
        pip3 install -r zephyr/scripts/requirements.txt
        
    - name: Build project
      run: |
        west build -p auto -b nucleo_h723zg ssl_firmware
        
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: build/zephyr/zephyr.*
